name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install node modules
        run: npm install
      - name: Build
        run: npm run build
      - name: Create version file
        working-directory: ./dist
        run: echo ${{ github.sha }} > version.txt
      - name: Package
        working-directory: ./dist
        run: tar cf - * | bzip2 -9 > dist.tar.bz2
      - name: Upload dist package
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/dist.tar.bz2
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist package
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.tar.bz2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
