name: Deliver
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the release to deliver'
        required: true

jobs:
  build:
    name: Deliver
    runs-on: ubuntu-latest
    steps:
      - name: Check release name (from release event)
        if: github.event_name == 'release'
        run: echo "release_name=$RELEASE_NAME" >> $GITHUB_ENV
        env: 
          RELEASE_NAME: ${{ github.event.release.name }}
      - name: Check release name (from dispatch event)
        if: github.event_name == 'workflow_dispatch'
        run: echo "release_name=$RELEASE_NAME" >> $GITHUB_ENV
        env: 
          RELEASE_NAME: ${{ github.event.inputs.release_name }}
      - name: Download release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ env.release_name }}
          file: dist.tar.bz2
          target: ./dist.tar.bz2
      - name: List files
        run: ls -al
   